#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.

if [[ -s "${ZDOTDIR:-$HOME}/git/dotfiles/libs/prezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/git/dotfiles/libs/prezto/init.zsh"
fi

# Customize to your needs...


source "${ZDOTDIR:-$HOME}/git/dotfiles/zsh/aliases.zsh"

autoload -Uz promptinit
promptinit
prompt steeef

